[project]
name = "translate-model"
version = "0.1.0"
description = "Translation model"
readme = "README.md"
requires-python = "==3.11.16"
authors = [
    { name = "Your Name", email = "you@example.com" }
]
# Core application requirements go here
dependencies = [
    "onnx>=1.22.0",
    "optimum[onnxruntime]>=2.1.0",
    "torch>=2.14.0",
    "transformers>=4.57.6",
]

[tool.setuptools]
packages = ["qwen_model", "indictrans2_model", "IndicTransToolkit", "it2_quantized_int8"]

[project.scripts]
run-script = "test_model:run_translation"

[tool.uv]
package = true
